export const wineries = [
  {
    name: "Alheit Vinyards",
    coords: "34°20′33″S 19°18′10″E",
    location: "Hermanus",
    key: "alheitvinyards",
  },
  {
    name: "Ambeloui",
    coords: "34.033434°S 18.366283°E",
    location: "Constantia",
    key: "ambeloui",
  },
  {
    name: "Akkerdal",
    coords: "33°52′43″S 19°2′57″E",
    location: "Franschhoek",
    key: "akkerdal",
  },
  {
    name: "Allee Bleue Winery",
    coords: "33°51′55″S 18°58′47″E",
    location: "Franschhoek",
    key: "alleebleuewinery",
  },
  {
    name: "Antikes",
    coords: "33°49′27.0″S 18°34′52.6″E",
    location: "Durbanville",
    key: "antikes",
  },
  {
    name: "Anwilka",
    coords: "",
    location: "Stellenbosch",
    key: "anwilka",
  },
  {
    name: "Atlas Swift",
    coords: "33°54′50″S 19°5′13″E",
    location: "Franschhoek",
    key: "atlasswift",
  },
  {
    name: "Augusta",
    coords: "33°53′35″S 19°5′41″E",
    location: "Franschhoek",
    key: "augusta",
  },
  {
    name: "Axe Hill Winery",
    coords: "33°30′58″S 21°41′22″E",
    location: "Calitszdorp",
    key: "axehillwinery",
  },
  {
    name: "Backsberg Estate Cellars",
    coords: "33°49′42.8″S 18°54′53″E",
    location: "Paarl and Wellington",
    key: "backsbergestatecellars",
  },
  {
    name: "Badsberg Wine Cellar",
    coords: "33°50′14″S 18°54′51″E",
    location: "Rawsonville",
    key: "badsbergwinecellar",
  },
  {
    name: "Beau Constantia",
    coords: "",
    location: "Constantia",
    key: "beauconstantia",
  },
  {
    name: "Beyerskloof Wine Farm",
    coords: "33°53′28″S 18°49′23.6″E",
    location: "Stellenbosch",
    key: "beyerskloofwinefarm",
  },
  {
    name: "Bloemendal",
    coords: "33°50′22.6″S 18°36′2.8″E",
    location: "Durbanville",
    key: "bloemendal",
  },
  {
    name: "Boplaas Winery and Distillery",
    coords: "33°32′07″S 21°41′01″E",
    location: "Calitszdorp",
    key: "boplaaswineryanddistillery",
  },
  {
    name: "Boschendal",
    coords: "33°52′39″S 18°58′22″E",
    location: "Franschhoek",
    key: "boschendal",
  },
  {
    name: "Bosman Family Vineyards",
    coords: "33°37′34″S 19°1′29″E",
    location: "Paarl and Wellington",
    key: "bosmanfamilyvineyards",
  },
  {
    name: "Bon Courage Wine Estate",
    coords: "33°50′43.8″S 19°57′38″E",
    location: "Robertson",
    key: "boncouragewineestate",
  },
  {
    name: "Bonfoi",
    coords: "33°53′31″S 18°46′29″E",
    location: "Stellenbosch",
    key: "bonfoi",
  },
  {
    name: "Boekenhoutskloof Winery",
    coords: "33°56′33″S 19°6′28″E",
    location: "Franschhoek",
    key: "boekenhoutskloofwinery",
  },
  {
    name: "Buitenverwachting",
    coords: "34°1′4″S 18°24′24″E",
    location: "Constantia",
    key: "buitenverwachting",
  },
  {
    name: "Camberley Wines",
    coords: "34°0′19″S 19°2′15″E",
    location: "Somerset West",
    key: "camberleywines",
  },
  {
    name: "Cederberg Private Cellar",
    coords: "32°31′5.2″S 19°14′7.7″E",
    location: "Cederberg",
    key: "cederbergprivatecellar",
  },
  {
    name: "Chamonix Wine Farm",
    coords: "34°4′14″S 19°4′20″E",
    location: "Franschhoek",
    key: "chamonixwinefarm",
  },
  {
    name: "Chapman's Peak Estate",
    coords: "34°5′58″S 18°23′3″E",
    location: "Constantia",
    key: "chapmanspeakestate",
  },
  {
    name: "Cloof Wine Estate",
    coords: "32°46′11″S 18°50′38″E",
    location: "Darling",
    key: "cloofwineestate",
  },
  {
    name: "Constantia Glen",
    coords: "34°0′44″S 18°24′33″E",
    location: "Constantia",
    key: "constantialglen",
  },
  {
    name: "Creation Wines",
    coords: "34°17′46.6″S 19°14′48.1″E",
    location: "Hermanus",
    key: "creationwines",
  },
  {
    name: "Dalla Cia Wine and Spirit Company",
    coords: "33°53′54″S 18°51′37″E",
    location: "Stellenbosch",
    key: "dallaciawineandspiritcompany",
  },
  {
    name: "De Wetshof Estate",
    coords: "33°45′58″S 20°1′1″E",
    location: "Robertson",
    key: "dewetshofestate",
  },
  {
    name: "De Toren Private Cellar",
    coords: "34°4′53.2″S 18°56′59.2″E",
    location: "Stellenbosch",
    key: "detorenprivatecellar",
  },
  {
    name: "De Wetshof Estate",
    coords: "33°45′58″S 20°1′1″E",
    location: "Robertson",
    key: "dewetshofestate",
  },
  {
    name: "De Wetshof Estate",
    coords: "33°45′58″S 20°1′1″E",
    location: "Robertson",
    key: "dewetshofestate",
  },
  {
    name: "De Morgenzon",
    coords: "33°56′0″S 18°54′2″E",
    location: "Stellenbosch",
    key: "demorgenzon",
  },
  {
    name: "Delaire Graff Estate",
    coords: "33°55′42″S 18°55′26″E",
    location: "Stellenbosch",
    key: "delairegraffestate",
  },
  {
    name: "Diemersdal Estate",
    coords: "33°48′18″S 18°32′26″E",
    location: "Durbanville",
    key: "diemersdalestate",
  },
  {
    name: "Doolhof Wine Estate",
    coords: "33°33′51.6″S 19°9′25.4″E",
    location: "Wellington",
    key: "doolhofwineestate",
  },
  {
    name: "Dornier Wines",
    coords: "33°57′43″S 18°53′22″E",
    location: "Stellenbosch",
    key: "dornierwines",
  },
  {
    name: "Druk-My-Niet Wine Estate",
    coords: "33°55′41″S 18°50′45″E",
    location: "Stellenbosch",
    key: "druk-mynietwineestate",
  },
  {
    name: "Du Toitskloof Winery",
    coords: "33°38′44″S 19°8′59″E",
    location: "Wellington",
    key: "dutoitskloofwinery",
  },
  {
    name: "Eagles' Nest",
    coords: "34°0′15″S 18°24′26″E",
    location: "Constantia",
    key: "eaglesnest",
  },
  {
    name: "Eikendal Vineyards",
    coords: "34°3′40″S 18°52′48″E",
    location: "Stellenbosch",
    key: "eikendalvineyards",
  },
  {
    name: "Elgin Vintners",
    coords: "34°10′39″S 19°0′5″E",
    location: "Elgin",
    key: "elginvintners",
  },
  {
    name: "Ernie Els Wines",
    coords: "34°1′45″S 18°51′59″E",
    location: "Stellenbosch",
    key: "ernieelswines",
  },
  {
    name: "Ernst Gouws & Co",
    coords: "34°2′44″S 18°51′18″E",
    location: "Stellenbosch",
    key: "ernstgouws&co",
  },
  {
    name: "Fairview Wine and Cheese",
    coords: "33°53′48″S 18°51′50″E",
    location: "Stellenbosch",
    key: "fairviewwineandcheese",
  },
  {
    name: "Flagstone Winery",
    coords: "34°2′34″S 18°50′51″E",
    location: "Stellenbosch",
    key: "flagstonewinery",
  },
  {
    name: "Glen Carlou Vineyards",
    coords: "33°50′5″S 19°5′13″E",
    location: "Paarl and Wellington",
    key: "glencarlouvineyards",
  },
  {
    name: "Groot Constantia",
    coords: "34°1′0″S 18°25′0″E",
    location: "Constantia",
    key: "grootconstantia",
  },
  {
    name: "Haute Cabrière",
    coords: "33°52′48.7″S 19°5′34.5″E",
    location: "Franschhoek",
    key: "hautecabrière",
  },
  {
    name: "Hidden Valley Wines",
    coords: "33°54′16″S 18°53′51″E",
    location: "Stellenbosch",
    key: "hiddenvalleywines",
  },
  {
    name: "Hillcrest Estate",
    coords: "34°0′46″S 18°26′5″E",
    location: "Durbanville",
    key: "hillcrestestate",
  },
  {
    name: "Iona Wine Farm",
    coords: "34°21′41″S 19°9′36″E",
    location: "Elgin",
    key: "ionawinefarm",
  },
  {
    name: "Jordan Wine Estate",
    coords: "33°57′44″S 18°53′26″E",
    location: "Stellenbosch",
    key: "jordanwineestate",
  },
  {
    name: "Kaapzicht Wine Estate",
    coords: "33°48′33″S 18°43′27″E",
    location: "Stellenbosch",
    key: "kaapzichtwineestate",
  },
  {
    name: "Kanonkop Wine Estate",
    coords: "33°54′0″S 18°53′0″E",
    location: "Stellenbosch",
    key: "kanonkopwineestate",
  },
  {
    name: "Klein Constantia Estate",
    coords: "34°1′7.3″S 18°25′16.1″E",
    location: "Constantia",
    key: "kleinconstantiaestate",
  },
  {
    name: "Kleine Zalze Wine Estate",
    coords: "33°55′0″S 18°51′0″E",
    location: "Stellenbosch",
    key: "kleinezalzewineestate",
  },
  {
    name: "La Motte",
    coords: "33°52′52″S 19°9′16″E",
    location: "Franschhoek",
    key: "lamotte",
  },
  {
    name: "Laibach Vineyards",
    coords: "34°2′56″S 18°51′55″E",
    location: "Stellenbosch",
    key: "laibachvineyards",
  },
  {
    name: "Lammershoek",
    coords: "32°17′39.5″S 18°53′21.5″E",
    location: "Swartland",
    key: "lammershoek",
  },
  {
    name: "L'Avenir Wine Estate",
    coords: "33°52′0″S 18°53′0″E",
    location: "Stellenbosch",
    key: "l'avenirwineestate",
  },
  {
    name: "Leopard's Leap",
    coords: "33°53′41″S 18°50′23″E",
    location: "Stellenbosch",
    key: "leopard'sleap",
  },
  {
    name: "Longridge Wine Estate",
    coords: "33°53′43″S 18°50′29″E",
    location: "Stellenbosch",
    key: "longridgewineestate",
  },
  {
    name: "Môreson",
    coords: "34°0′57″S 19°0′34″E",
    location: "Franschhoek",
    key: "môreson",
  },
  {
    name: "Muratie Wine Estate",
    coords: "33°52′36″S 18°54′16″E",
    location: "Stellenbosch",
    key: "muratiewineestate",
  },
  {
    name: "Neil Ellis Wines",
    coords: "34°4′20″S 18°51′53″E",
    location: "Stellenbosch",
    key: "neilelliswines",
  },
  {
    name: "Newton Johnson Vineyards",
    coords: "34°29′55.1″S 19°15′9.4″E",
    location: "Hemel-en-Aarde Valley",
    key: "newtonjohnsonvineyards",
  },
  {
    name: "Noble Hill Wine Estate",
    coords: "34°4′21″S 18°52′24″E",
    location: "Paarl",
    key: "noblehillwineestate",
  },
  {
    name: "Oldenburg Vineyards",
    coords: "33°53′16.4″S 18°55′28.5″E",
    location: "Stellenbosch",
    key: "oldenburgvineyards",
  },
  {
    name: "Painted Wolf Wines",
    coords: "33°47′48″S 18°53′8″E",
    location: "Paarl",
    key: "paintedwolfwines",
  },
  {
    name: "Paul Cluver Wines",
    coords: "34°10′5.6″S 19°5′35.1″E",
    location: "Elgin",
    key: "paulcluverwines",
  },
  {
    name: "Paul Wallace Wines",
    coords: "34°0′24.6″S 19°8′24.1″E",
    location: "Elgin",
    key: "paulwallacewines",
  },
  {
    name: "Peter Falke Wines",
    coords: "33°52′55″S 18°53′16″E",
    location: "Stellenbosch",
    key: "peterfalkewines",
  },
  {
    name: "Quoin Rock",
    coords: "34°1′36″S 18°50′5″E",
    location: "Stellenbosch",
    key: "quoinrock",
  },
  {
    name: "Raka Wine",
    coords: "34°30′52″S 19°15′1″E",
    location: "Klein River",
    key: "rakawine",
  },
  {
    name: "Rust en Vrede",
    coords: "34°0′39″S 18°51′7″E",
    location: "Stellenbosch",
    key: "rustenvrede",
  },
  {
    name: "Rustenberg Wines",
    coords: "33°53′39″S 18°53′31″E",
    location: "Stellenbosch",
    key: "rustenbergwines",
  },
 

 {
    name: "Rusthof",
    coords: "33°50′0″S 19°2′0″E",
    location: "Franschhoek",
    key: "rusthof",
  },
  {
    name: "Saronsberg Cellar",
    coords: "33°29′45″S 19°19′47″E",
    location: "Tulbagh",
    key: "saronsbergcellar",
  },
  {
    name: "Saronsberg Wine Estate",
    coords: "33°29′45″S 19°19′47″E",
    location: "Tulbagh",
    key: "saronsbergwineestate",
  },
  {
    name: "Saxenburg Wine Estate",
    coords: "33°50′0″S 18°43′0″E",
    location: "Kuils River",
    key: "saxenburgwineestate",
  },
  {
    name: "Simonsig Wine Estate",
    coords: "33°54′20″S 18°50′22″E",
    location: "Stellenbosch",
    key: "simonsigwineestate",
  },
  {
    name: "Skilpadvlei Wine Farm",
    coords: "33°55′0″S 18°49′0″E",
    location: "Stellenbosch",
    key: "skilpadvleiwinefarm",
  },
  {
    name: "Slanghoek Cellar",
    coords: "33°21′44″S 19°18′59″E",
    location: "Rawsonville",
    key: "slanghoekcellar",
  },
  {
    name: "Solms-Delta",
    coords: "33°45′48″S 18°52′6″E",
    location: "Franschhoek",
    key: "solms-delta",
  },
  {
    name: "Spice Route",
    coords: "33°43′59.9″S 18°58′0.2″E",
    location: "Paarl",
    key: "spiceroute",
  },
  {
    name: "Spier Wine Farm",
    coords: "33°59′50″S 18°43′18″E",
    location: "Stellenbosch",
    key: "spierwinefarm",
  },
  {
    name: "Springfield Estate",
    coords: "34°1′1″S 19°25′20″E",
    location: "Robertson",
    key: "springfieldestate",
  },
  {
    name: "Stark-Condé Wines",
    coords: "33°56′49.5″S 18°54′55.5″E",
    location: "Stellenbosch",
    key: "stark-condéwines",
  },
  {
    name: "Steenberg Vineyards",
    coords: "34°4′26″S 18°25′0″E",
    location: "Constantia",
    key: "steenbergvineyards",
  },
  {
    name: "Stellenrust Wine Estate",
    coords: "33°55′6″S 18°52′3″E",
    location: "Stellenbosch",
    key: "stellenrustwineestate",
  },
  {
    name: "Strandveld Vineyards",
    coords: "34°29′29″S 19°23′51″E",
    location: "Elim",
    key: "strandveldvineyards",
  },
  {
    name: "Sumaridge Estate Wines",
    coords: "34°28′41.1″S 19°15′38.9″E",
    location: "Hemel-en-Aarde Valley",
    key: "sumaridgeestatewines",
  },
  {
    name: "Thelema Mountain Vineyards",
    coords: "33°53′56″S 18°52′51″E",
    location: "Stellenbosch",
    key: "thelemamountainvineyards",
  },
  {
    name: "Tokara",
    coords: "34°2′39″S 18°54′10″E",
    location: "Stellenbosch",
    key: "tokara",
  },
  {
    name: "Uva Mira",
    coords: "34°2′49″S 18°55′17″E",
    location: "Stellenbosch",
    key: "uvamira",
  },
  {
    name: "Vergelegen Estate",
    coords: "34°4′4″S 18°52′28″E",
    location: "Somerset West",
    key: "vergelegenestate",
  },
  {
    name: "Villiera",
    coords: "33°51′57″S 18°52′41″E",
    location: "Stellenbosch",
    key: "villiera",
  },
  {
    name: "Vredenheim Wine Estate",
    coords: "33°53′18″S 18°50′42″E",
    location: "Stellenbosch",
    key: "vredenheimwineestate",
  },
  {
    name: "Waterford Estate",
    coords: "33°53′30″S 18°54′42″E",
    location: "Stellenbosch",
    key: "waterfordestate",
  },
  {
    name: "Zorgvliet Wines",
    coords: "33°53′28″S 18°53′33″E",
    location: "Stellenbosch",
    key: "zorgvlietwines",
  },
];